name = "searxng"
main = "src/index.js"
compatibility_date = "2024-10-22"
compatibility_flags = ["nodejs_compat"]

[[containers]]
name = "searxng"
class_name = "SearxNGContainer"
image = "ghcr.io/searxng/searxng:latest"
instance_type = "basic"
autoscaling = { minimum_instances = 1, cpu_target = 0.6 }
env = { FORCE_OWNERSHIP = "false", CONFIG_PATH = "/tmp/config", DATA_PATH = "/tmp/data" }

[[durable_objects.bindings]]
name = "SEARXNG_CONTAINER"
class_name = "SearxNGContainer"

[[migrations]]
tag = "v1"
new_sqlite_classes = ["SearxNGContainer"]
